<a href="https://colab.research.google.com/github/MOHAMMADSALIK18/data-science-journey/blob/main/Numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
arr = a1 / a2
arr

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
arr=a1//a2
arr

array([0, 0, 0, 0, 0])

### What is Broadcasting? (Simple explanation)

Imagine you have a list of numbers, and you want to add a single number to each item in that list. Instead of writing code to go through each item one by one, NumPy's **broadcasting** lets you do this automatically.

It's like NumPy is smart enough to see that you want to add the single number to *every* element of the list, even though they don't look exactly the same shape. It *stretches* the single number (conceptually) to match the size of the list, then performs the operation.

### `np.hsplit()` (Horizontal Split)

*   `np.hsplit()` divides an array into multiple sub-arrays **horizontally**, meaning it cuts the array along its **columns**.
*   Imagine cutting a cake *vertically* through its layers to get slices side-by-side. Each slice still has all the layers.

### `np.vsplit()` (Vertical Split)

*   `np.vsplit()` divides an array into multiple sub-arrays **vertically**, meaning it cuts the array along its **rows**.
*   Imagine cutting a cake *horizontally* across its layers to separate the top half from the bottom half. Each piece is a row or group of rows.

**Key Difference:**
*   `hsplit` changes the **number of columns** in the resulting sub-arrays.
*   `vsplit` changes the **number of rows** in the resulting sub-arrays.

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr1=arr+10
arr1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [ ]:
arr1=arr*10
arr1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300]])

**Matrix Operation**

In [ ]:
A=np.array([[1,2],[4,5]])
B=np.array([[10,20],[40,50]])


In [ ]:
A.T

array([[1, 4],
       [2, 5]])

In [ ]:
A,B,

(array([[1, 2],
        [4, 5]]),
 array([[10, 20],
        [40, 50]]))

In [ ]:
A*B

array([[ 10,  40,  90],
       [160, 250, 360]])

In [ ]:
A @ B


array([[ 90, 120],
       [240, 330]])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [ ]:
np.hstack(  (a,b)  )

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack(  (a,b)  )

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.column_stack(  (a,b)  )

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
a=np.arange(16).reshape(4,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
import numpy as np

# Let's re-create our example array 'a' for clarity
a = np.arange(16).reshape(4,4)
print("Original Array 'a':\n", a)
print("--------------------\n")

# Using np.hsplit(a, 2) - Splits 'a' into 2 sub-arrays horizontally (column-wise)
print("Result of np.hsplit(a, 2) - Each sub-array has fewer columns:\n")
h_splits = np.hsplit(a, 2)
for i, sub_array in enumerate(h_splits):
    print(f"Horizontal Split {i+1}:\n", sub_array)
print("--------------------\n")

# Using np.vsplit(a, 2) - Splits 'a' into 2 sub-arrays vertically (row-wise)
# (changed from 4 to 2 for a clearer example of separating rows into chunks)
print("Result of np.vsplit(a, 2) - Each sub-array has fewer rows:\n")
v_splits = np.vsplit(a, 2)
for i, sub_array in enumerate(v_splits):
    print(f"Vertical Split {i+1}:\n", sub_array)
print("--------------------\n")

Original Array 'a':
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------

Result of np.hsplit(a, 2) - Each sub-array has fewer columns:

Horizontal Split 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Horizontal Split 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------------------

Result of np.vsplit(a, 2) - Each sub-array has fewer rows:

Vertical Split 1:
 [[0 1 2 3]
 [4 5 6 7]]
Vertical Split 2:
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------

