<a href="https://colab.research.google.com/github/MOHAMMADSALIK18/data-science-journey/blob/main/Nuympy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy indexing and slicing of vectors**

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

**Numpy indexingand slicing of matrix**

In [ ]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
arr[4:6,4:6]

array([[29, 30],
       [35, 36]])

In [ ]:
arr[:,3]

array([ 4, 10, 16, 22, 28, 34])

**Boolean Indexing**

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [4]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])